---
title: "Matricula"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
pacman::p_load(flexdashboard, shiny, dplyr, plotly)
```


```{r data}

data <- read.csv("BankChurners.csv")
base_matriculas <-readRDS("matricula.Rds") %>% 
  mutate(def_f=factor(deficiencia))

Categorical.Variables = c("Gender", "Education_Level", "Marital_Status")

variavel.categorica = c("agua_grande", "cantagalo")

variavel.escolhida = c("idade", "def_f", "Distrito",
                       "Nome_da_escola")

Numeric.Variables = c("Customer_Age", "Total_Trans_Ct", "Credit_Limit")

```


Column {.sidebar data-width=200}
-------------------------------------------------------------------
```{r}

selectInput(inputId="categorical_variable", label = "Select Categorical Variable:", choices = Categorical.Variables, selected = Categorical.Variables[1])

selectInput(inputId="distrito_escolhido", label = "Escolha o distrito", choices = variavel.categorica, selected = variavel.categorica[1])

selectInput(inputId="variavel_escolhida", label = "Escolha uma variavel", choices = variavel.escolhida, selected = variavel.escolhida[1])

#selectInput(inputId="numeric_variable", label = "Select Numeric Variable:", choices = Numeric.Variables, selected = Numeric.Variables[1])

```

Column {data-width=400}
-------------------------------------------------------------------

### **Box plot** shows the relationship between categorical and numeric variables
```{r}

renderPlotly({
  plot_ly(base_matriculas,
              x = ~base_matriculas[[input$variavel_escolhida]],
                type = "box") %>%
  layout(title = "",
         xaxis = list(title = "" ,
                      zeroline = FALSE))
})

#renderPlotly({
#  plot_ly(data,
#              x = ~data[[input$numeric_variable]],
#              color = #~data[[input$categorical_variable]],
#              colors = "Paired",
#              type = "box") %>%
#  layout(title = "",
#         xaxis = list(title = "" ,
#                      zeroline = FALSE))
#})
```

Column {data-width=400}
-------------------------------------------------------------------

### **Bar chart** shows the distribution of categorical veriable
```{r}

renderPlotly({
  data %>%
    count(var = data[[input$categorical_variable]], name = "count") %>%
    plot_ly( x = ~var, y = ~ count, type = "bar", marker = list(color = '#008ae6',
                           line = list(color = '#008ae6', width = 2)), hoverinfo = "x+y") %>%
    add_text(text = ~paste0( " (",   scales::percent(count/sum(count)),")"), 
           textposition = "bottom", 
           textfont = list(size = 12, color = "white"), 
           showlegend = FALSE) %>%
    layout(xaxis = list(title = ""), yaxis = list(title = ""))
    
})
```

### **Histogram** shows the distribution of numeric variable
```{r}

base_matriculas2 <- reactive(
  base_matriculas["Distrito" %in% input$distrito_escolhido,])


renderPlotly({
  plot_ly(x = data[[input$variavel_escolhida]], type = "histogram",  marker = list(color = "#008ae6",
                            line = list(color = "darkgray",
                                        width = 1)))
})
```